apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
  namespace: static
spec:
  selector:
    matchLabels:
      app: static
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image:861431775398.dkr.ecr.us-east-2.amazonaws.com/k8s:12
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static
  namespace: static
spec:
  selector: 
    app: static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

